#!/bin/bash
 
## compiler: ssc-0.0.1-b9
## host: Darwin YupyeSortaco.local 24.1.0 Darwin Kernel Version 24.1.0: Mon Sep  2 19:57:26 PDT 2024; root:xnu-11215.40.48~33/RELEASE_ARM64_T8112 arm64 arm Darwin
## date: 20240922T101629Z
 
#!/bin/bash

Slibsh_PrintJudgement_AnswerNo () 
{ 
    Slibsh_PrintJudgement_Base;
    echo $Slibsh_printJudgement_answerNo
}
Slibsh_PrintJudgement_AnswerYes () 
{ 
    Slibsh_PrintJudgement_Base;
    echo $Slibsh_printJudgement_answerYes
}
Slibsh_PrintJudgement_Architecture () 
{ 
    Slibsh_PrintJudgement_Base;
    Slibsh_PrintJudgement_SentenceBeginning;
    echo -n "the architecture of this host is $1";
    Slibsh_PrintJudgement_SentenceEnding
}
Slibsh_PrintJudgement_Base () 
{ 
    export Slibsh_printJudgement_sentenceBeginning="Checking whether ";
    export Slibsh_printJudgement_sentenceEnding="... ";
    export Slibsh_printJudgement_answerYes="yes";
    export Slibsh_printJudgement_answerNo="no"
}
Slibsh_PrintJudgement_Existence () 
{ 
    Slibsh_PrintJudgement_Base;
    Slibsh_PrintJudgement_SentenceBeginning;
    echo -n "$1 exists";
    Slibsh_PrintJudgement_SentenceEnding
}
Slibsh_PrintJudgement_Os () 
{ 
    Slibsh_PrintJudgement_Base;
    Slibsh_PrintJudgement_SentenceBeginning;
    echo -n "the OS on this host is $1";
    Slibsh_PrintJudgement_SentenceEnding
}
Slibsh_PrintJudgement_SentenceBeginning () 
{ 
    Slibsh_PrintJudgement_Base;
    echo -n "$Slibsh_printJudgement_sentenceBeginning"
}
Slibsh_PrintJudgement_SentenceEnding () 
{ 
    Slibsh_PrintJudgement_Base;
    echo -n "$Slibsh_printJudgement_sentenceEnding"
}
Slibsh_PrintJudgement_Version () 
{ 
    Slibsh_PrintJudgement_Base;
    Slibsh_PrintJudgement_SentenceBeginning;
    [ -z "$2" ] && echo -n "the version is $1";
    [ -n "$2" ] && echo -n "the version of $1 is $2";
    Slibsh_PrintJudgement_SentenceEnding
}
Slibsh_PrintMessage () 
{ 
    echo -n "$1: ";
    [[ "$2" = d* ]] && echo -en "\e[1m\e[037mdebug: \e[0m";
    [[ "$2" = i* ]] && echo -en "\e[1m\e[092minfo: \e[0m";
    [[ "$2" = w* ]] && echo -en "\e[1m\e[093mwarning: \e[0m";
    [[ "$2" = e* ]] && echo -en "\e[1m\e[091merror: \e[0m";
    [[ "$2" = f* ]] && echo -en "\e[1m\e[031mfafal: \e[0m";
    echo "$3"
}
Slibsh_PrintMessage_Debug () 
{ 
    Slibsh_PrintMessage "$1" d "$2"
}
Slibsh_PrintMessage_Error () 
{ 
    Slibsh_PrintMessage "$1" e "$2"
}
Slibsh_PrintMessage_Fafal () 
{ 
    Slibsh_PrintMessage "$1" f "$2"
}
Slibsh_PrintMessage_Fafal_InvalidExtensionName () 
{ 
    Slibsh_PrintMessage_Fafal "$1" "Invalid extension name in \`$2'."
}
Slibsh_PrintMessage_Fafal_ItemExists () 
{ 
    Slibsh_PrintMessage_Fafal "$1" "\`$2' exists."
}
Slibsh_PrintMessage_Fafal_ItemNotFound () 
{ 
    Slibsh_PrintMessage_Fafal "$1" "\`$2' not found."
}
Slibsh_PrintMessage_Fafal_SourceExpected () 
{ 
    Slibsh_PrintMessage_Fafal "$1" "Source expected."
}
Slibsh_PrintMessage_Fafal_TargetExpected () 
{ 
    Slibsh_PrintMessage_Fafal "$1" "Target expected."
}
Slibsh_PrintMessage_Fafal_TooManyArguments () 
{ 
    Slibsh_PrintMessage_Fafal "$1" "To many arguments."
}
Slibsh_PrintMessage_Info () 
{ 
    Slibsh_PrintMessage "$1" i "$2"
}
Slibsh_PrintMessage_Warning () 
{ 
    Slibsh_PrintMessage "$1" w "$2"
}
Ssc_CheckFiles () 
{ 
    [ ! -f "$ssc_source" ] && Slibsh_PrintMessage_Fafal_ItemNotFound "$0" "$ssc_source" && exit 1;
    [ -f "$ssc_target" ] && Slibsh_PrintMessage_Fafal_ItemExists "$0" "$ssc_target" && exit 1;
    [ ! "${ssc_source: -5}" = ".s.sh" ] && Slibsh_PrintMessage_Fafal_InvalidExtensionName "$0" "$ssc_source" && exit 1
}
Ssc_CheckParameters () 
{ 
    if [ "$#" -ne 2 ]; then
        if [ "$#" -eq 0 ]; then
            Slibsh_PrintMessage_Fafal_SourceExpected "$0";
        else
            if [ "$#" -eq 1 ]; then
                Slibsh_PrintMessage_Fafal_TargetExpected "$0";
            else
                if [ "$#" -gt 2 ]; then
                    Slibsh_PrintMessage_Fafal_TooManyArguments "$0";
                fi;
            fi;
        fi;
        exit 1;
    fi
}
Ssc_DeleteComments () 
{ 
    sed -i '/#/!b;s/^/\n/;ta;:a;s/\n$//;t;s/\n\(\("[^"]*"\)\|\('\''[^'\'']*'\''\)\)/\1\n/;ta;s/\n\([^#]\)/\1\n/;ta;s/\n.*//' "$1"
}
Ssc_PrintBrand () 
{ 
    echo "$ssc_name (Soras Shell Compiler $ssc_version) $ssc_version";
    echo "Copyright (C) 2024 Tarikko-ScetayhChan";
    echo "This is free software; see the source for copying conditions.  There is NO";
    echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
}
Ssc_WriteCompilationInformation () 
{ 
    sed -i "1i\## date: $(date +%Y%m%dT%H%M%SZ)" "$ssc_target";
    sed -i "1i\## host: $(uname -a)" "$ssc_target";
    sed -i "1i\## compiler: $ssc_name-$ssc_version" "$ssc_target";
    sed -i '1i\#!/bin/bash' "$ssc_target";
    sed -i '1a\ ' "$ssc_target";
    sed -i '5a\ ' "$ssc_target"
}

export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

function CheckCommandLineTool() {
    Slibsh_PrintJudgement_Existence "$2"
    if [ -f "$(which "$2")" ]; then
        Slibsh_PrintJudgement_AnswerYes
    else
        Slibsh_PrintJudgement_AnswerNo
        Slibsh_PrintMessage_Fafal_ItemNotFound "$1" "$2"
        echo "Install the latest $2 for $OS_TYPE."
        exit 1
    fi
}

function DownloadDotnet() {
    if wget https://dot.net/v1/dotnet-install.sh; then
        if ! bash dotnet-install.sh "$1"; then
            echo "Error: Cannot install .NET $1 for $OS_TYPE."
            exit 1
        fi
    else
        echo "Error: Cannot download dotnet-install scripts."
        echo "You should check the network connection or use a proxy."
        exit 1
    fi
}

function CheckDotnetRuntime() {
    echo -n "Checking whether .NET Runtime '$1' 8.0 for $OS_TYPE has been installed... "
    if dotnet --list-runtimes | grep "$1 8.0." &> /dev/null; then
        echo "yes"
    else
        echo "no"
        DownloadDotnet "Runtime 8.0.0" "--runtime dotnet --version 8.0.0"
    fi
}

if true; then

    # To enter ~/.fdnr
    export FORMER_DIRECTORY="$PWD"
    mkdir -p ~/.fdnr
    cd ~/.fdnr || exit 1

    # To check $ARCH
    if [ -n "$ARCH" ]; then
        if [ ! "$ARCH" = "x86" ];then
            if [ ! "$ARCH" = "x64" ]; then
                if [ ! "$ARCH" = "arm64" ]; then
                    echo "Error: $ARCH is not an available architecture."
                    exit 1
                fi
            fi
        fi
    else
        export ARCH=x64
    fi

    # To check OS type
    echo -n "Checking OS type... "
    if [ ! -e /System ]; then
        export OS_TYPE="GNU/Linux"
    else
        export OS_TYPE="Darwin (macOS)"
    fi
    echo "$OS_TYPE"

    # To Set environment variables
    export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

    # To Check Git and Wget
    CheckCommandLineTool "$0" git
    CheckCommandLineTool "$0" wget

    # To check .NET SDK 8.0 for $OS_TYPE
    echo -n "Checking whether .NET SDK 8.0 for $OS_TYPE has been installed... "
    if dotnet --list-sdks | grep "8.0." &> /dev/null; then
        echo "yes"
    else
        echo "no"
        DownloadDotnet "SDK 8.0" "--channel 8.0"
    fi

    # To check .NET Runtime 8.0 for $OS_TYPE
    CheckDotnetRuntime Microsoft.AspNetCore.App
    CheckDotnetRuntime Microsoft.NETCore.App

    # To clone repository
    echo -n "Checking whether repository has been cloned... "
    if [ -d FishDeskNextReborn ]; then
        echo "yes"
    else
        echo "no"
        echo "Cloning 'https://github.com/liziyu0714/FishDeskNextReborn.git'..."
        rm -rf FishDeskNextReborn
        if ! git clone https://github.com/liziyu0714/FishDeskNextReborn.git; then
            echo "Error: Cannot clone repository 'https://github.com/liziyu0714/FishDeskNextReborn.git'."
            echo "You should check the network connection or use a proxy."
            exit 1
        fi
    fi

    # To build project
    cd FishDeskNextReborn || exit 1
    if ! dotnet publish --arch "$ARCH" --os win --framework net8.0-windows; then
        echo "Error: Cannot publish the project."
        echo "You should wait for a while and operate 'dotnet publish --arch x64 --os win' again."
        exit 1
    fi
    echo "Successfully published the project."
    echo "Go to '~/.fdnr/FishDeskNextReborn/src/FishDeskNextReborn/bin/Release/net8.0-windows/win-x64/' to check the products."
    echo "Now you can copy the directory above to your Windows platform."
    echo "Thank you for using this script ☆ Kira~"
    cd "$FORMER_DIRECTORY" || exit 1

fi