#!/bin/bash
# SPDX-License-Identifier: GPL-3.0

if true; then
    if [ ! -e /System ]; then
        echo " * OS type: GNU/Linux"
        export OS_TYPE="GNU/Linux"
    else
        echo " * OS type: Darwin (macOS)"
        export OS_TYPE="Darwin (macOS)"
    fi

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

    echo -n " * Checking whether Git has been installed... "
    if [ -f "$(which git)" ]; then
        echo "yes"
    else
        echo "no"
        echo "Error: Git not found."
        echo "Install the latest Git for $OS_TYPE."
        exit 1
    fi

    echo -n " * Checking whether .NET SDK 8.0 for $OS_TYPE has been installed... "
    if [ ! -z "$(dotnet --list-sdks | grep "8.0.")" ]; then
        echo "yes"
    else
        echo "no"
        echo "Error: .NET SDK 8.0 for $OS_TYPE not found."
        echo "Go to https://dotnet.microsoft.com/zh-cn/download/dotnet/8.0 to install .NET SDK 8.0 for $OS_TYPE."
        exit 1
    fi

    echo -n " * Checking whether .NET Runtime 'Microsoft.AspNetCore.App' 8.0 for $OS_TYPE has been installed... "
    if [ ! -z "$(dotnet --list-runtimes | grep "Microsoft.AspNetCore.App 8.0.")" ]; then
        echo "yes"
    else
        echo "no"
        echo "Error: .NET Runtime 'Microsoft.AspNetCore.App' 8.0 for $OS_TYPE not found."
        echo "Go to https://dotnet.microsoft.com/zh-cn/download/dotnet/8.0 to install .NET Runtime 8.0 for $OS_TYPE."
        exit 1
    fi

    echo -n " * Checking whether .NET Runtime 'Microsoft.NETCore.App' 8.0 for $OS_TYPE has been installed... "
    if [ ! -z "$(dotnet --list-runtimes | grep "Microsoft.NETCore.App 8.0.")" ]; then
        echo "yes"
    else
        echo "no"
        echo "Error: .NET Runtime 'Microsoft.NETCore.App' 8.0 for $OS_TYPE not found."
        echo "Go to https://dotnet.microsoft.com/zh-cn/download/dotnet/8.0 to install .NET Runtime 8.0 for $OS_TYPE."
        exit 1
    fi

    echo " * Cloning 'https://github.com/liziyu0714/FishDeskNextReborn.git'..."
    export FORMER_DIRECTORY="$PWD"
    mkdir -p ~/.fdnr
    cd ~/.fdnr
    rm -rf FishDeskNextReborn
    git clone https://github.com/liziyu0714/FishDeskNextReborn.git

    if [ ! $? -eq 0 ]; then
        echo "Error: Cannot clone 'https://github.com/liziyu0714/FishDeskNextReborn.git'."
        echo "You should check the network connection or use a proxy."
        exit 1
    fi

    cd FishDeskNextReborn
    dotnet publish --arch x64 --os win

    if [ ! $? -eq 0 ]; then
        echo "Error: Cannot publish the project."
        echo "You should wait for a while and operate 'dotnet publish --arch x64 --os win' again."
        exit 1
    fi

    echo " * Successfully published the project."
    echo "Go to '~/.fdnr/FishDeskNextReborn/src/FishDeskNextReborn/bin/Release/net8.0-windows/win-x64/' to check the products."
    echo "Now you can copy the products to your Windows platform. Good luck!"
    cd $FORMER_DIRECTORY
fi